services:
  - type: web
    name: smart-traffic-signal-optimization
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 8 --timeout 120
    autoDeploy: true
